export { RESUME_JSON_SCHEMA_STRING, resumeJsonSchema } from './json-schema.ts';
export {
  type AwardInput,
  type AwardOutput,
  AwardSchema,
  type BasicsInput,
  type BasicsOutput,
  BasicsSchema,
  type ContactInput,
  type ContactOutput,
  ContactSchema,
  type ItemBlockInput,
  type ItemBlockOutput,
  ItemBlockSchema,
  type ItemLinkInput,
  type ItemLinkOutput,
  ItemLinkSchema,
  RESUME_SCHEMA_VERSION,
  type ResumeInput,
  type ResumeMetaInput,
  type ResumeMetaOutput,
  ResumeMetaSchema,
  type ResumeOutput,
  ResumeSchema,
  SKILL_LEVELS,
  type SkillItemInput,
  type SkillItemOutput,
  SkillItemSchema,
  type SkillSectionInput,
  type SkillSectionOutput,
  SkillSectionSchema,
} from './schema.ts';
export {
  FALLBACK_TEMPLATE_CONFIG,
  type ResolvedTemplateConfig,
  resolveTemplateConfig,
  type TemplateConfig,
  type TemplateConfigOverrides,
  TemplateConfigOverridesSchema,
  TemplateConfigSchema,
} from './template-config.ts';
export type { ResumeData } from './types.ts';
