name: Semifold CI
on:
  push:
    branches: [main]

env:
  CLICOLOR_FORCE: 1

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build:
    name: Version or Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
      - name: Setup Semifold
        uses: noctisynth/setup-semifold@main
        with:
          version: v0.3.0-beta.3
      - name: Semifold CI
        run: semifold ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
