name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary
      - run: bun install --frozen-lockfile
      - run: bun run check
      - run: bun run test
      - run: bun run typsume build examples/sample/resume.json
